name: Mproj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip
  - pip:
    - splipy
    - libigl
    - jax[cpu]
    - jaxlib
    - geomdl
    - ipykernel
    - ipywidgets
    - jupyterlab
    - -e ./Chakana_Geo/hanan
    - -e ./Chakana_Geo/kayviz
